The Founder's Journey: The Story of Creepy
My journey with Creepy began not as a developer, but as a moderator for a massive 800,000+ member gaming community for a major studio. I learned firsthand that even with a dedicated team, you can't be everywhere at once. I saw vibrant communities slowly lose their spark and engagement fade.
The problem became personal when I created my own private community server for beta testing. In the beginning, it was crowded and active, but over time, it died. Standard interaction bots were not enough; no one cared. This is the problem I set out to solve.
The Spark: The First Alpha
I began testing the first version of Creepy on that same "dead" server. The change was immediate. Members came back to try and guess the riddles. They engaged with the economy. The server came back to life. This was the validation I needed. From this, I developed "Creepy's Heartbeat," an innovative feature designed to seek out lulls in server activity and proactively launch high-stake mini-events to keep people engaged.
The First Platform: Rapid Growth on Firebase
Creepy was initially developed and built on Firebase, an incredible platform for rapid prototyping. The Gemini chat and code assistant tools were my primary partners, building everything from the dashboard to the backend logic. But the bot became more and more complex. With 32 commands (now 42), the project's complexity eventually outgrew what the initial Firebase setup could handle, leading to a critical crash during a command overhaul.
The Crisis & The Pivot
I spent days digging through logs, attempting to reset the VM, and writing forensic reports for the support team, but the issue was unresolvable. The project was too big.
In a last-ditch effort, I packed up the entire Creepy project and force-uploaded it to a private GitHub repository. I cloned it into a standalone Google Cloud VM and began the painstaking process of rebuilding. After several failed attempts to redeploy on Firebase, it became clear that Creepy had evolved beyond its first home. I made the strategic decision to stop trying to force it and instead fully embrace the more robust, scalable infrastructure of a standalone GCloud VM.
The Evolution: GCloud and the Future
Since migrating, I have continued to improve the codebase, add new features, and adopt more advanced tools like the Gemini CLI or Google JULES to help debug and write new features. I've professionalized the stack by migrating from a standard Gemini API key to a secure Vertex AI integration and implemented a full YouTube API music player.
My final attempt to use Firebase for a simple dashboard last week confirmed my decision. The platform, while great for starting, began to hallucinate on a project of this scale, overriding complex .env files and proving it was not reliable for our needs.
Creepy is now a large, complex, and battle-tested project. This journey—from moderation, to validation, to crisis and recovery—is the foundation upon which we are building its future.
